//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroBASICDriver {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class RetroBASICConsoleSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static RetroBASICConsoleSettings defaultInstance = ((RetroBASICConsoleSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RetroBASICConsoleSettings())));
        
        public static RetroBASICConsoleSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultBASICProgramDirectory {
            get {
                return ((string)(this["DefaultBASICProgramDirectory"]));
            }
            set {
                this["DefaultBASICProgramDirectory"] = value;
            }
        }
    }
}
